plugins:
  topic_list_thumbnails:
    default: false
    client: true
  topic_list_excerpts:
    default: false
    client: true
  topic_list_actions:
    default: false
    client: true
  topic_list_category_badge_move:
    default: false
    client: true
  topic_list_show_like_on_current_users_posts:
    default: false
    client: true
  topic_list_excerpt_length:
    default: 200
    client: true
  topic_list_default_thumbnail:
    default: ''
    client: true
  topic_list_thumbnail_width:
    default: 100
    client: true
  topic_list_thumbnail_height:
    default: 100
    client: true
  topic_list_social_feed:
    default: false
    client: true
